<a href="https://colab.research.google.com/github/Anisha31415/dsml/blob/main/Day29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#eigen vector and eigen value
#when eigen value matrix multiply by another matrixim

In [7]:
import numpy as np

A=np.array((
     [1,2],
     [3,4]
))
eigenvalues,  eigenvectors=np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

In [8]:
#eigenvector drawbacks= works on square not rectangle
#SVD-Singular Value Decomposition- decompose(rotate,stretch,rotate)
#A=UEVt=
#E summation e and transpose of V
U, S, V = np.linalg.svd(A)
print("U matrix:\n", U)
print("sigma values:", S)
print("V matrix:\n", V)

U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
sigma values: [5.4649857  0.36596619]
V matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

In [9]:
print(U @ U.T)

[[1.00000000e+00 3.00701513e-16]
 [3.00701513e-16 1.00000000e+00]]

In [ ]:
#pip install pandas

In [34]:
import pandas as pd
a=['g','e','e','k','s']
res=pd.Series(a)
print(res)

0    g
1    e
2    e
3    k
4    s
dtype: object

In [18]:
dict={"name:":"ani","age  :":20,"number:":3344}
res=pd.Series(dict)# series gives data in one dimension
print(res)

name:       ani
age  :       20
number:    3344
dtype: object

In [13]:
res.ndim

1

In [21]:
res_data=pd.DataFrame(res, columns=["data1"])
print(res_data)

        data1
name:     ani
age  :     20
number:  3344

In [23]:
#res_data['data1'].isnull().sum()

np.int64(0)

In [32]:
a={
   "Name": ["Defoe","J.terry","Lampard"],
   "Team": ["Newcastle","Chelsea", "Chelesa"],
   "Number": [23,5,22],
   "Age:": [33,38,31]
}
df=pd.DataFrame(a)
print(df)

      Name       Team  Number  Age:
0    Defoe  Newcastle      23    33
1  J.terry    Chelsea       5    38
2  Lampard    Chelesa      22    31

In [43]:
df[["Team","Number"]]
df

      Name       Team  Number  Age:
0    Defoe  Newcastle      23    33
1  J.terry    Chelsea       5    38
2  Lampard    Chelesa      22    31

In [39]:
df['Team'].isna()

0    False
1    False
2    False
Name: Team, dtype: bool

In [41]:
print(df["Team"].isna().sum())

0

In [50]:
res=df.loc[df['Name']=='Defoe']
res

    Name  Age     Team
0  Defoe   20  Chelsea

In [47]:
#loc and iloc
#DataFrame save to csv format
a={
    "Name":["Defoe","Terry"],
    "Age":[20,22],
    "Team":["Chelsea", "Newcastle"]
}
df=pd.DataFrame(a)
df.to_csv("data.csv")

In [48]:
data=pd.read_csv("data.csv")
print(data)

   Unnamed: 0   Name  Age       Team
0           0  Defoe   20    Chelsea
1           1  Terry   22  Newcastle